language: node_js
node_js:
  - "0.12"
  - "1"
  - "2"
  - "3"
  - "4"
  - "6"
  - "10"
notifications:
  email:
    on_success: change
    on_failure: change
sudo: false
after_success:
  - npm install -g codecov
  - codecov
